import { NestFactory } from '@nestjs/core';
import { Model } from 'mongoose';
import { getModelToken } from '@nestjs/mongoose';
import * as bcrypt from 'bcrypt';
import { AppModule } from '../app.module';
import { User, UserRole } from '../users/schemas/user.schema';
import { ProProfile, PricingModel } from '../pro-profile/schemas/pro-profile.schema';
import { Job, JobStatus, JobBudgetType, JobSizeUnit, JobPropertyType } from '../jobs/schemas/job.schema';
import { PortfolioItem, ProjectType, ProjectStatus } from '../portfolio/schemas/portfolio-item.schema';
import { Company, CompanyStatus, CompanySize } from '../company/schemas/company.schema';
import { CompanyEmployee, EmployeeRole, EmployeeStatus } from '../company/schemas/company-employee.schema';
import { CompanyJob, CompanyJobStatus, JobPriority } from '../company/schemas/company-job.schema';
import { Category } from '../categories/schemas/category.schema';

async function seed() {
  console.log('🌱 Starting seed...');

  const app = await NestFactory.createApplicationContext(AppModule);

  const userModel = app.get<Model<User>>(getModelToken(User.name));
  const proProfileModel = app.get<Model<ProProfile>>(getModelToken(ProProfile.name));
  const jobModel = app.get<Model<Job>>(getModelToken(Job.name));
  const portfolioModel = app.get<Model<PortfolioItem>>(getModelToken(PortfolioItem.name));
  const companyModel = app.get<Model<Company>>(getModelToken(Company.name));
  const companyEmployeeModel = app.get<Model<CompanyEmployee>>(getModelToken(CompanyEmployee.name));
  const companyJobModel = app.get<Model<CompanyJob>>(getModelToken(CompanyJob.name));
  const categoryModel = app.get<Model<Category>>(getModelToken(Category.name));

  // Clear existing data
  console.log('🗑️  Clearing existing data...');
  await categoryModel.deleteMany({});
  await proProfileModel.deleteMany({});
  await portfolioModel.deleteMany({});
  await companyJobModel.deleteMany({});
  await companyEmployeeModel.deleteMany({});
  await companyModel.deleteMany({});
  await userModel.deleteMany({ role: UserRole.PRO });
  await userModel.deleteMany({ role: UserRole.COMPANY });

  // Seed categories
  console.log('📁 Seeding categories...');
  const categories = [
    {
      key: 'interior-design',
      name: 'Designer',
      nameKa: 'დიზაინერი',
      description: 'Interior and exterior designers',
      descriptionKa: 'ინტერიერისა და ექსტერიერის დიზაინერები',
      icon: 'designer',
      sortOrder: 1,
      isActive: true,
    },
    {
      key: 'architecture',
      name: 'Architect',
      nameKa: 'არქიტექტორი',
      description: 'Architects and structural engineers',
      descriptionKa: 'არქიტექტორები და კონსტრუქტორები',
      icon: 'architect',
      sortOrder: 2,
      isActive: true,
    },
    {
      key: 'craftsmen',
      name: 'Craftsmen',
      nameKa: 'ხელოსანი',
      description: 'Skilled tradespeople',
      descriptionKa: 'კვალიფიციური ხელოსნები',
      icon: 'craftsmen',
      sortOrder: 3,
      isActive: true,
    },
    {
      key: 'home-care',
      name: 'Services',
      nameKa: 'სერვისები',
      description: 'Home services and maintenance',
      descriptionKa: 'სახლის მომსახურება და მოვლა',
      icon: 'homecare',
      sortOrder: 4,
      isActive: true,
    },
  ];

  await categoryModel.insertMany(categories);
  console.log(`✅ Created ${categories.length} categories`);

  const hashedPassword = await bcrypt.hash('demo123', 10);

  // Helper to generate unique 11-digit ID numbers
  let idCounter = 10000000001;
  const generateIdNumber = () => String(idCounter++);

  // Demo client and admin users
  const demoUsers = [
    {
      name: 'Demo Client',
      email: 'client@demo.com',
      password: hashedPassword,
      role: UserRole.CLIENT,
      phone: '+995 555 123 456',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Demo Admin',
      email: 'admin@demo.com',
      password: hashedPassword,
      role: UserRole.ADMIN,
      phone: '+995 555 345 678',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
  ];

  // Additional client users for portfolio variety
  const clientUsers = [
    {
      name: 'Lasha Gachechiladze',
      email: 'lasha.client@demo.com',
      password: hashedPassword,
      role: UserRole.CLIENT,
      phone: '+995 555 111 001',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Maka Lortkipanidze',
      email: 'maka.client@demo.com',
      password: hashedPassword,
      role: UserRole.CLIENT,
      phone: '+995 555 111 002',
      city: 'Batumi',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Vakhtang Mdivani',
      email: 'vakhtang.client@demo.com',
      password: hashedPassword,
      role: UserRole.CLIENT,
      phone: '+995 555 111 003',
      city: 'Kutaisi',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Natia Beridze',
      email: 'natia.client@demo.com',
      password: hashedPassword,
      role: UserRole.CLIENT,
      phone: '+995 555 111 004',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Giorgi Kvachadze',
      email: 'giorgi.client@demo.com',
      password: hashedPassword,
      role: UserRole.CLIENT,
      phone: '+995 555 111 005',
      city: 'Rustavi',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Salome Kakabadze',
      email: 'salome.client@demo.com',
      password: hashedPassword,
      role: UserRole.CLIENT,
      phone: '+995 555 111 006',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Tornike Basilashvili',
      email: 'tornike.client@demo.com',
      password: hashedPassword,
      role: UserRole.CLIENT,
      phone: '+995 555 111 007',
      city: 'Batumi',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Eka Tabatadze',
      email: 'eka.client@demo.com',
      password: hashedPassword,
      role: UserRole.CLIENT,
      phone: '+995 555 111 008',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
  ];

  // Comprehensive list of professional users
  const proUsers = [
    {
      name: 'Giorgi Beridze',
      email: 'giorgi@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 111 222',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Nino Kvaratskhelia',
      email: 'nino@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 333 444',
      city: 'Batumi',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Davit Lomidze',
      email: 'davit@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 555 666',
      city: 'Kutaisi',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Mariam Tsiklauri',
      email: 'mariam@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 777 888',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Luka Javakhishvili',
      email: 'luka@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 999 000',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Ana Khachaturyan',
      email: 'ana@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 222 333',
      city: 'Rustavi',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Nikoloz Gelashvili',
      email: 'nikoloz@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 444 555',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Tamari Kiknadze',
      email: 'tamari@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 666 777',
      city: 'Batumi',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Irakli Mghebrishvili',
      email: 'irakli@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 888 999',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Elene Nozadze',
      email: 'elene@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 111 444',
      city: 'Kutaisi',
      avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Zura Papashvili',
      email: 'zura@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 222 555',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Ketevan Shengelia',
      email: 'ketevan@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 333 666',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Giga Tevzadze',
      email: 'giga@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 444 777',
      city: 'Batumi',
      avatar: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Sophio Datunashvili',
      email: 'sophio@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 555 888',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Levan Mchedlishvili',
      email: 'levan@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 666 999',
      city: 'Rustavi',
      avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Nana Chikvaidze',
      email: 'nana@demo.com',
      password: hashedPassword,
      role: UserRole.PRO,
      phone: '+995 555 777 111',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
  ];

  const allUsers = [...demoUsers, ...clientUsers, ...proUsers];

  // Create or update users
  const createdUsers: User[] = [];

  for (const userData of allUsers) {
    let user = await userModel.findOne({ email: userData.email });

    if (user) {
      console.log(`📝 Updating user: ${userData.email}`);
      await userModel.updateOne({ email: userData.email }, userData);
      user = await userModel.findOne({ email: userData.email });
    } else {
      console.log(`✨ Creating user: ${userData.email}`);
      user = await userModel.create(userData);
    }

    createdUsers.push(user!);
  }

  // Pro profiles with comprehensive data
  const proProfiles = [
    {
      email: 'giorgi@demo.com',
      profile: {
        title: 'Master Electrician',
        companyName: 'ElectroTech Georgia',
        description: 'Certified electrician with 15 years of experience. Specializing in residential and commercial electrical work, smart home installations, and electrical safety inspections.',
        categories: ['craftsmen'],
        subcategories: ['electrical', 'hvac'],
        yearsExperience: 15,
        serviceAreas: ['Tbilisi', 'Rustavi', 'Mtskheta'],
        pricingModel: PricingModel.HOURLY,
        basePrice: 45,
        currency: 'GEL',
        avgRating: 4.9,
        totalReviews: 127,
        completedJobs: 342,
        externalCompletedJobs: 580,
        responseTime: '< 1 hour',
        isAvailable: true,
        coverImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&h=400&fit=crop',
        certifications: ['Certified Electrician', 'Smart Home Specialist', 'Safety Inspector'],
        languages: ['Georgian', 'English', 'Russian'],
        tagline: 'Safe and professional electrical solutions',
        companies: [{ name: 'ElectroTech Georgia', logo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=100&h=100&fit=crop', role: 'Founder' }],
        portfolioProjects: [
          { title: 'Smart Home Installation', description: 'Complete smart home system', location: 'Tbilisi', images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800', 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800'], videos: [] },
          { title: 'Office Electrical Upgrade', description: 'Full office rewiring', location: 'Saburtalo', images: ['https://images.unsplash.com/photo-1621905252472-943afaa20e20?w=800', 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800'], videos: [] },
          { title: 'Panel Installation', description: 'New electrical panel', location: 'Vake', images: ['https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800'], videos: [] },
        ],
      },
    },
    {
      email: 'nino@demo.com',
      profile: {
        title: 'Interior Designer',
        companyName: 'Nino Design Studio',
        description: 'Award-winning interior designer creating beautiful, functional spaces. Specializing in modern minimalist and contemporary Georgian design. Full-service from concept to completion.',
        categories: ['interior-design'],
        subcategories: ['interior', 'exterior', '3d-visualization'],
        yearsExperience: 8,
        serviceAreas: ['Batumi', 'Tbilisi', 'Kobuleti'],
        pricingModel: PricingModel.PROJECT_BASED,
        basePrice: 150,
        currency: 'GEL',
        avgRating: 5.0,
        totalReviews: 89,
        completedJobs: 156,
        externalCompletedJobs: 230,
        responseTime: '< 2 hours',
        isAvailable: true,
        coverImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&h=400&fit=crop',
        certifications: ['Interior Design Diploma', 'AutoCAD Certified', '3D Visualization Expert'],
        languages: ['Georgian', 'English', 'Turkish'],
        tagline: 'Transforming spaces, creating dreams',
        companies: [{ name: 'Nino Design Studio', logo: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=100&h=100&fit=crop', role: 'Creative Director' }],
        portfolioProjects: [
          { title: 'Modern Apartment Design', description: 'Minimalist apartment in Batumi', location: 'Batumi', images: ['https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800', 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800', 'https://images.unsplash.com/photo-1615529328331-f8917597711f?w=800'], videos: [] },
          { title: 'Boutique Hotel Lobby', description: 'Luxury hotel redesign', location: 'Batumi', images: ['https://images.unsplash.com/photo-1615529328331-f8917597711f?w=800', 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800'], videos: [] },
          { title: 'Living Room Makeover', description: 'Contemporary living space', location: 'Kobuleti', images: ['https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800', 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800'], videos: [] },
        ],
      },
    },
    {
      email: 'davit@demo.com',
      profile: {
        title: 'Plumbing Expert',
        companyName: 'Aqua Solutions',
        description: 'Professional plumber with expertise in residential and commercial plumbing. Emergency repairs, pipe installation, bathroom renovations, and heating systems.',
        categories: ['craftsmen'],
        subcategories: ['plumbing'],
        yearsExperience: 12,
        serviceAreas: ['Kutaisi', 'Tbilisi', 'Zestafoni', 'Samtredia'],
        pricingModel: PricingModel.FROM,
        basePrice: 35,
        currency: 'GEL',
        avgRating: 4.7,
        totalReviews: 203,
        completedJobs: 578,
        externalCompletedJobs: 920,
        responseTime: '< 30 min',
        isAvailable: true,
        coverImage: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=1200&h=400&fit=crop',
        certifications: ['Master Plumber License', 'Gas Safe Registered'],
        languages: ['Georgian', 'Russian'],
        tagline: '24/7 emergency plumbing service',
        companies: [{ name: 'Aqua Solutions', logo: '', role: 'Owner' }],
        portfolioProjects: [
          { title: 'Bathroom Renovation', description: 'Complete bathroom plumbing overhaul', location: 'Kutaisi', images: ['https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800', 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800'], videos: [] },
          { title: 'Kitchen Sink Install', description: 'New sink and dishwasher connection', location: 'Tbilisi', images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800'], videos: [] },
        ],
      },
    },
    {
      email: 'mariam@demo.com',
      profile: {
        title: 'Renovation Specialist',
        companyName: 'ProBuild Georgia',
        description: 'Complete home renovation services. From planning to execution, we handle everything including demolition, construction, electrical, plumbing, and finishing work.',
        categories: ['craftsmen'],
        subcategories: ['painting', 'flooring', 'plastering'],
        yearsExperience: 10,
        serviceAreas: ['Tbilisi', 'Rustavi', 'Mtskheta'],
        pricingModel: PricingModel.PROJECT_BASED,
        basePrice: 80,
        currency: 'GEL',
        avgRating: 4.8,
        totalReviews: 156,
        completedJobs: 234,
        externalCompletedJobs: 450,
        responseTime: '< 3 hours',
        isAvailable: true,
        coverImage: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=1200&h=400&fit=crop',
        certifications: ['Licensed Contractor', 'Safety Certified', 'Project Management'],
        languages: ['Georgian', 'English', 'Russian'],
        tagline: 'Your complete renovation partner',
        companies: [{ name: 'ProBuild Georgia', logo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=100&h=100&fit=crop', role: 'Project Manager' }],
        portfolioProjects: [
          { title: 'Full Apartment Renovation', description: '85sqm apartment makeover', location: 'Saburtalo', images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800', 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800'], videos: [] },
          { title: 'Bedroom Renovation', description: 'Master bedroom redesign', location: 'Rustavi', images: ['https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800', 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'], videos: [] },
          { title: 'Wall Painting Project', description: '3-room interior painting', location: 'Mtskheta', images: ['https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800'], videos: [] },
        ],
      },
    },
    {
      email: 'luka@demo.com',
      profile: {
        title: 'HVAC Technician',
        companyName: '',
        description: 'Heating, ventilation, and air conditioning specialist. Installation, maintenance, and repair of all HVAC systems. Energy-efficient solutions for homes and offices.',
        categories: ['craftsmen'],
        subcategories: ['hvac'],
        yearsExperience: 7,
        serviceAreas: ['Tbilisi', 'Rustavi'],
        pricingModel: PricingModel.HOURLY,
        basePrice: 50,
        currency: 'GEL',
        avgRating: 4.6,
        totalReviews: 78,
        completedJobs: 189,
        responseTime: '< 2 hours',
        isAvailable: true,
        coverImage: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=1200&h=400&fit=crop',
        certifications: ['HVAC Certified', 'EPA Certified'],
        languages: ['Georgian', 'English'],
        tagline: 'Climate control experts',
        companies: [],
        portfolioProjects: [
          { title: 'Central AC Installation', description: 'Office building AC system', location: 'Tbilisi', images: ['https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800', 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800', 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800'], videos: [] },
          { title: 'Heat Pump Installation', description: 'Energy-efficient heating', location: 'Rustavi', images: ['https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'], videos: [] },
        ],
      },
    },
    {
      email: 'ana@demo.com',
      profile: {
        title: 'Kitchen Designer',
        companyName: 'Kitchen Dreams',
        description: 'Specialized in kitchen design and renovation. Custom cabinetry, countertops, appliance installation, and complete kitchen makeovers. Free 3D visualization included.',
        categories: ['interior-design'],
        subcategories: ['interior', 'furniture-design', '3d-visualization'],
        yearsExperience: 6,
        serviceAreas: ['Rustavi', 'Tbilisi'],
        pricingModel: PricingModel.PROJECT_BASED,
        basePrice: 200,
        currency: 'GEL',
        avgRating: 4.9,
        totalReviews: 67,
        completedJobs: 98,
        responseTime: '< 4 hours',
        isAvailable: true,
        coverImage: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=400&fit=crop',
        certifications: ['Kitchen Design Specialist', 'AutoCAD Certified'],
        languages: ['Georgian', 'Russian', 'English'],
        tagline: 'Creating your dream kitchen',
        companies: [{ name: 'Kitchen Dreams', logo: '', role: 'Lead Designer' }],
        portfolioProjects: [
          { title: 'Modern Kitchen Renovation', description: 'Complete kitchen redesign with custom cabinets', location: 'Tbilisi', images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800', 'https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=800', 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800'], videos: [] },
          { title: 'Minimalist Kitchen', description: 'Sleek modern design with hidden storage', location: 'Rustavi', images: ['https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800', 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800'], videos: [] },
        ],
      },
    },
    {
      email: 'nikoloz@demo.com',
      profile: {
        title: 'Roofing Contractor',
        companyName: 'Top Roof Georgia',
        description: 'Professional roofing services including installation, repair, and maintenance. Expertise in tile, metal, and flat roofing. Waterproofing and insulation specialists.',
        categories: ['craftsmen'],
        subcategories: ['roofing'],
        yearsExperience: 14,
        serviceAreas: ['Tbilisi', 'Mtskheta', 'Rustavi', 'Gardabani'],
        pricingModel: PricingModel.FROM,
        basePrice: 25,
        currency: 'GEL',
        avgRating: 4.5,
        totalReviews: 112,
        completedJobs: 287,
        externalCompletedJobs: 520,
        responseTime: '< 1 hour',
        isAvailable: true,
        coverImage: 'https://images.unsplash.com/photo-1632759145351-1d592919f522?w=1200&h=400&fit=crop',
        certifications: ['Licensed Roofer', 'Fall Protection Certified'],
        languages: ['Georgian', 'Russian'],
        tagline: 'Protecting your home from above',
        companies: [{ name: 'Top Roof Georgia', logo: '', role: 'Founder' }],
        portfolioProjects: [
          { title: 'Roof Replacement', description: 'Full tile roof replacement', location: 'Tbilisi', images: ['https://images.unsplash.com/photo-1632759145351-1d592919f522?w=800', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800'], videos: [] },
          { title: 'Metal Roof Install', description: 'Modern metal roofing', location: 'Mtskheta', images: ['https://images.unsplash.com/photo-1558036117-15d82a90b9b1?w=800', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800'], videos: [] },
          { title: 'Leak Repair', description: 'Emergency roof repair', location: 'Rustavi', images: ['https://images.unsplash.com/photo-1632759145351-1d592919f522?w=800'], videos: [] },
        ],
      },
    },
    {
      email: 'tamari@demo.com',
      profile: {
        title: 'Landscape Architect',
        companyName: 'Green Gardens',
        description: 'Creating beautiful outdoor spaces. Garden design, lawn care, irrigation systems, outdoor lighting, and hardscaping. Sustainable and eco-friendly approaches.',
        categories: ['interior-design'],
        subcategories: ['landscape-design', 'exterior'],
        yearsExperience: 9,
        serviceAreas: ['Batumi', 'Kobuleti', 'Ozurgeti'],
        pricingModel: PricingModel.PROJECT_BASED,
        basePrice: 120,
        currency: 'GEL',
        avgRating: 4.8,
        totalReviews: 54,
        completedJobs: 89,
        responseTime: '< 6 hours',
        isAvailable: true,
        coverImage: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=1200&h=400&fit=crop',
        certifications: ['Landscape Architecture Degree', 'Irrigation Specialist'],
        languages: ['Georgian', 'English', 'Turkish'],
        tagline: 'Nature meets design',
        companies: [{ name: 'Green Gardens', logo: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=100&h=100&fit=crop', role: 'Lead Architect' }],
        portfolioProjects: [
          { title: 'Seaside Garden Design', description: 'Mediterranean garden with pool area', location: 'Batumi', images: ['https://images.unsplash.com/photo-1558904541-efa843a96f01?w=800', 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800', 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800'], videos: [] },
          { title: 'Private Villa Landscaping', description: 'Complete outdoor living space', location: 'Kobuleti', images: ['https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800', 'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=800'], videos: [] },
        ],
      },
    },
    {
      email: 'irakli@demo.com',
      profile: {
        title: 'Painting Professional',
        companyName: '',
        description: 'Interior and exterior painting services. Wallpaper installation, texture finishes, and decorative painting. High-quality materials and attention to detail.',
        categories: ['craftsmen'],
        subcategories: ['painting'],
        yearsExperience: 11,
        serviceAreas: ['Tbilisi', 'Rustavi', 'Mtskheta'],
        pricingModel: PricingModel.FROM,
        basePrice: 15,
        currency: 'GEL',
        avgRating: 4.7,
        totalReviews: 189,
        completedJobs: 456,
        responseTime: '< 2 hours',
        isAvailable: true,
        coverImage: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=1200&h=400&fit=crop',
        certifications: ['Certified Painter', 'Lead Paint Certified'],
        languages: ['Georgian', 'Russian'],
        tagline: 'Color your world',
        companies: [],
        portfolioProjects: [
          { title: 'Full Apartment Painting', description: '3-room apartment interior painting', location: 'Tbilisi', images: ['https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800', 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800'], videos: [] },
          { title: 'Exterior House Painting', description: 'Full exterior paint with weatherproofing', location: 'Rustavi', images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800', 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800'], videos: [] },
        ],
      },
    },
    {
      email: 'elene@demo.com',
      profile: {
        title: 'Flooring Specialist',
        companyName: 'Perfect Floors',
        description: 'Expert flooring installation - hardwood, laminate, tile, and vinyl. Floor refinishing and repair services. Heated floor systems installation.',
        categories: ['craftsmen'],
        subcategories: ['flooring', 'tiling'],
        yearsExperience: 8,
        serviceAreas: ['Kutaisi', 'Tbilisi', 'Zestafoni'],
        pricingModel: PricingModel.FROM,
        basePrice: 20,
        currency: 'GEL',
        avgRating: 4.6,
        totalReviews: 98,
        completedJobs: 234,
        responseTime: '< 3 hours',
        isAvailable: false,
        coverImage: 'https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=1200&h=400&fit=crop',
        certifications: ['Flooring Installation Certified', 'Tile Setter License'],
        languages: ['Georgian', 'English'],
        tagline: 'The foundation of beautiful homes',
        companies: [{ name: 'Perfect Floors', logo: '', role: 'Installer' }],
        portfolioProjects: [
          { title: 'Hardwood Floor Installation', description: 'Oak flooring in luxury apartment', location: 'Kutaisi', images: ['https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=800', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800'], videos: [] },
          { title: 'Tile Floor Project', description: 'Large-format tile installation', location: 'Tbilisi', images: ['https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800', 'https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=800'], videos: [] },
        ],
      },
    },
    {
      email: 'zura@demo.com',
      profile: {
        title: 'Carpentry Expert',
        companyName: 'Wood Masters',
        description: 'Custom woodworking and carpentry services. Built-in furniture, doors, windows, and staircases. Restoration of antique wooden items.',
        categories: ['craftsmen'],
        subcategories: ['carpentry'],
        yearsExperience: 18,
        serviceAreas: ['Tbilisi', 'Mtskheta'],
        pricingModel: PricingModel.PROJECT_BASED,
        basePrice: 100,
        currency: 'GEL',
        avgRating: 4.9,
        totalReviews: 145,
        completedJobs: 312,
        responseTime: '< 4 hours',
        isAvailable: true,
        coverImage: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=1200&h=400&fit=crop',
        certifications: ['Master Carpenter', 'Furniture Making Diploma'],
        languages: ['Georgian', 'Russian', 'English'],
        tagline: 'Crafting excellence in wood',
        companies: [{ name: 'Wood Masters', logo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=100&h=100&fit=crop', role: 'Master Craftsman' }],
        portfolioProjects: [
          { title: 'Custom Built-In Closet', description: 'Full wall wardrobe system', location: 'Tbilisi', images: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'], videos: [] },
          { title: 'Staircase Renovation', description: 'Oak staircase with custom railing', location: 'Mtskheta', images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800'], videos: [] },
        ],
      },
    },
    {
      email: 'ketevan@demo.com',
      profile: {
        title: 'Home Inspector',
        companyName: 'SafeHome Inspections',
        description: 'Comprehensive home inspection services. Pre-purchase inspections, safety assessments, and detailed reports. Thermal imaging and moisture detection available.',
        categories: ['home-care'],
        subcategories: ['appliance-repair'],
        yearsExperience: 5,
        serviceAreas: ['Tbilisi', 'Rustavi', 'Mtskheta', 'Gardabani'],
        pricingModel: PricingModel.HOURLY,
        basePrice: 60,
        currency: 'GEL',
        avgRating: 4.8,
        totalReviews: 67,
        completedJobs: 178,
        responseTime: '< 2 hours',
        isAvailable: true,
        coverImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=400&fit=crop',
        certifications: ['Certified Home Inspector', 'Thermal Imaging Certified'],
        languages: ['Georgian', 'English', 'Russian'],
        tagline: 'Your home, thoroughly examined',
        companies: [{ name: 'SafeHome Inspections', logo: '', role: 'Lead Inspector' }],
        portfolioProjects: [
          { title: 'Pre-Purchase Inspection', description: 'Comprehensive home inspection', location: 'Tbilisi', images: ['https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800'], videos: [] },
          { title: 'Thermal Assessment', description: 'Infrared imaging inspection', location: 'Mtskheta', images: ['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800', 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800'], videos: [] },
        ],
      },
    },
    {
      email: 'giga@demo.com',
      profile: {
        title: 'Pool Services Technician',
        companyName: 'Aqua Pools',
        description: 'Complete pool services - installation, maintenance, and repair. Water treatment, equipment upgrades, and seasonal pool care. Serving the coastal region.',
        categories: ['home-care'],
        subcategories: ['gardening'],
        yearsExperience: 10,
        serviceAreas: ['Batumi', 'Kobuleti', 'Chakvi'],
        pricingModel: PricingModel.FROM,
        basePrice: 40,
        currency: 'GEL',
        avgRating: 4.5,
        totalReviews: 43,
        completedJobs: 89,
        responseTime: '< 3 hours',
        isAvailable: true,
        coverImage: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=1200&h=400&fit=crop',
        certifications: ['Pool Technician Certified', 'Water Treatment Specialist'],
        languages: ['Georgian', 'Russian', 'Turkish'],
        tagline: 'Dive into perfection',
        companies: [{ name: 'Aqua Pools', logo: '', role: 'Lead Technician' }],
        portfolioProjects: [
          { title: 'Luxury Pool Installation', description: 'Infinity pool in Batumi villa', location: 'Batumi', images: ['https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800', 'https://images.unsplash.com/photo-1572331165267-854da2b10ccc?w=800', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800'], videos: [] },
          { title: 'Pool Renovation', description: 'Complete pool upgrade', location: 'Kobuleti', images: ['https://images.unsplash.com/photo-1572331165267-854da2b10ccc?w=800', 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800'], videos: [] },
        ],
      },
    },
    {
      email: 'sophio@demo.com',
      profile: {
        title: 'Cleaning Professional',
        companyName: 'Sparkle Clean',
        description: 'Professional cleaning services for homes and offices. Deep cleaning, post-construction cleanup, and regular maintenance. Eco-friendly products available.',
        categories: ['home-care'],
        subcategories: ['cleaning', 'window-cleaning'],
        yearsExperience: 4,
        serviceAreas: ['Tbilisi', 'Rustavi'],
        pricingModel: PricingModel.HOURLY,
        basePrice: 25,
        currency: 'GEL',
        avgRating: 4.7,
        totalReviews: 234,
        completedJobs: 567,
        responseTime: '< 1 hour',
        isAvailable: true,
        coverImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&h=400&fit=crop',
        certifications: ['Professional Cleaner Certified'],
        languages: ['Georgian', 'Russian'],
        tagline: 'Spotless results guaranteed',
        companies: [{ name: 'Sparkle Clean', logo: '', role: 'Team Lead' }],
        portfolioProjects: [
          { title: 'Post-Construction Cleanup', description: 'Deep cleaning after renovation', location: 'Tbilisi', images: ['https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800', 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=800'], videos: [] },
          { title: 'Office Deep Clean', description: 'Complete office sanitization', location: 'Rustavi', images: ['https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=800', 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800'], videos: [] },
        ],
      },
    },
    {
      email: 'levan@demo.com',
      profile: {
        title: 'Security Systems Expert',
        companyName: 'SecureHome Georgia',
        description: 'Home and business security solutions. CCTV installation, alarm systems, smart locks, and access control. 24/7 monitoring services available.',
        categories: ['craftsmen'],
        subcategories: ['electrical'],
        yearsExperience: 9,
        serviceAreas: ['Rustavi', 'Tbilisi', 'Gardabani'],
        pricingModel: PricingModel.PROJECT_BASED,
        basePrice: 150,
        currency: 'GEL',
        avgRating: 4.6,
        totalReviews: 56,
        completedJobs: 123,
        responseTime: '< 2 hours',
        isAvailable: true,
        coverImage: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=1200&h=400&fit=crop',
        certifications: ['Security Systems Installer', 'Network Security Certified'],
        languages: ['Georgian', 'English', 'Russian'],
        tagline: 'Protecting what matters most',
        companies: [{ name: 'SecureHome Georgia', logo: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=100&h=100&fit=crop', role: 'Technical Director' }],
        portfolioProjects: [
          { title: 'Home Security System', description: 'Complete CCTV and alarm setup', location: 'Rustavi', images: ['https://images.unsplash.com/photo-1558002038-1055907df827?w=800', 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800', 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800'], videos: [] },
          { title: 'Office Access Control', description: 'Card access system installation', location: 'Tbilisi', images: ['https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800', 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800'], videos: [] },
        ],
      },
    },
    {
      email: 'nana@demo.com',
      profile: {
        title: 'Moving Specialist',
        companyName: 'Easy Move',
        description: 'Professional moving services - local and long-distance. Packing, loading, transport, and unpacking. Furniture assembly and disassembly included.',
        categories: ['home-care'],
        subcategories: ['moving'],
        yearsExperience: 6,
        serviceAreas: ['Tbilisi', 'Rustavi', 'Mtskheta', 'Kutaisi', 'Batumi'],
        pricingModel: PricingModel.FROM,
        basePrice: 100,
        currency: 'GEL',
        avgRating: 4.4,
        totalReviews: 89,
        completedJobs: 234,
        externalCompletedJobs: 380,
        responseTime: '< 1 hour',
        isAvailable: true,
        coverImage: 'https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=1200&h=400&fit=crop',
        certifications: ['Licensed Mover'],
        languages: ['Georgian', 'Russian'],
        tagline: 'Moving made simple',
        companies: [{ name: 'Easy Move', logo: '', role: 'Operations Manager' }],
        portfolioProjects: [
          { title: 'Office Relocation', description: 'Full office move with 50 workstations', location: 'Tbilisi', images: ['https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=800', 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800'], videos: [] },
          { title: 'Long Distance Move', description: 'Tbilisi to Batumi family relocation', location: 'Batumi', images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800'], videos: [] },
        ],
      },
    },
  ];

  for (const proData of proProfiles) {
    const user = createdUsers.find(u => u.email === proData.email);

    if (user) {
      console.log(`✨ Creating pro profile for: ${proData.email}`);
      await proProfileModel.create({
        ...proData.profile,
        userId: user._id,
      });
    }
  }

  // Create demo jobs
  const clientUser = createdUsers.find(u => u.email === 'client@demo.com');

  if (clientUser) {
    // Clear existing jobs from this client for clean seeding
    await jobModel.deleteMany({ clientId: clientUser._id });

    const demoJobs = [
      {
        clientId: clientUser._id,
        title: 'Full Apartment Renovation in Saburtalo',
        description: 'Need complete renovation of 85sqm apartment in Saburtalo district. Work includes: wall leveling and painting, ceiling installation, flooring (laminate), plumbing replacement, electrical rewiring. New construction, green frame.',
        category: 'renovation',
        skills: ['painting', 'flooring', 'plumbing', 'electrical'],
        location: 'Tbilisi, Saburtalo',
        propertyType: JobPropertyType.APARTMENT,
        areaSize: 85,
        sizeUnit: JobSizeUnit.SQUARE_METER,
        roomCount: 3,
        budgetType: JobBudgetType.PER_SQUARE_METER,
        pricePerUnit: 180,
        deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        status: JobStatus.OPEN,
        images: [
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
          'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        ],
        proposalCount: 5,
        viewCount: 124,
      },
      {
        clientId: clientUser._id,
        title: 'Kitchen Renovation and Cabinet Installation',
        description: 'Complete kitchen update: old tile removal, new tile installation, kitchen cabinet mounting (cabinets already purchased), sink and faucet installation, appliance connection.',
        category: 'kitchen',
        skills: ['tiling', 'furniture-assembly', 'plumbing'],
        location: 'Tbilisi, Vake',
        propertyType: JobPropertyType.APARTMENT,
        areaSize: 12,
        sizeUnit: JobSizeUnit.SQUARE_METER,
        budgetType: JobBudgetType.RANGE,
        budgetMin: 3000,
        budgetMax: 5000,
        deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        status: JobStatus.OPEN,
        images: [
          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
        ],
        proposalCount: 8,
        viewCount: 89,
      },
      {
        clientId: clientUser._id,
        title: 'Bathroom Renovation',
        description: 'Bathroom renovation on 6sqm area. Required: waterproofing, tile installation (walls and floor), plumbing installation (toilet, sink, shower cabin), water heater mounting.',
        category: 'bathroom',
        skills: ['tiling', 'plumbing', 'waterproofing'],
        location: 'Tbilisi, Didube',
        propertyType: JobPropertyType.APARTMENT,
        areaSize: 6,
        sizeUnit: JobSizeUnit.SQUARE_METER,
        roomCount: 1,
        budgetType: JobBudgetType.FIXED,
        budgetAmount: 4500,
        deadline: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000),
        status: JobStatus.OPEN,
        images: [
          'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800',
        ],
        proposalCount: 12,
        viewCount: 156,
      },
      {
        clientId: clientUser._id,
        title: 'Complete Electrical Rewiring',
        description: 'Complete electrical rewiring in 3-room apartment. Removal of old aluminum wiring and replacement with copper cable. New circuit breakers, outlets and switches installation.',
        category: 'electrical',
        skills: ['electrical', 'wiring'],
        location: 'Tbilisi, Gldani',
        propertyType: JobPropertyType.APARTMENT,
        areaSize: 65,
        sizeUnit: JobSizeUnit.SQUARE_METER,
        roomCount: 3,
        budgetType: JobBudgetType.PER_SQUARE_METER,
        pricePerUnit: 25,
        deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        status: JobStatus.OPEN,
        images: [],
        proposalCount: 3,
        viewCount: 67,
      },
      {
        clientId: clientUser._id,
        title: 'Private House Roof Repair',
        description: 'Private house roof repair after rain leak. Likely need to replace several tiles and renew waterproofing. Roof area approximately 120sqm.',
        category: 'roofing',
        skills: ['roofing', 'waterproofing'],
        location: 'Tbilisi, Tskneti',
        propertyType: JobPropertyType.HOUSE,
        areaSize: 120,
        sizeUnit: JobSizeUnit.SQUARE_METER,
        budgetType: JobBudgetType.RANGE,
        budgetMin: 2000,
        budgetMax: 4000,
        deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        status: JobStatus.OPEN,
        images: [
          'https://images.unsplash.com/photo-1632759145351-1d592919f522?w=800',
        ],
        proposalCount: 2,
        viewCount: 45,
      },
      {
        clientId: clientUser._id,
        title: 'Office Interior Design and Renovation',
        description: '150sqm office space design and renovation. Need interior designer and renovation team. Open space concept, 2 conference rooms, reception area, kitchen.',
        category: 'interior-design',
        skills: ['interior-design', 'renovation', 'painting', 'flooring'],
        location: 'Tbilisi, Vera',
        propertyType: JobPropertyType.OFFICE,
        areaSize: 150,
        sizeUnit: JobSizeUnit.SQUARE_METER,
        roomCount: 5,
        budgetType: JobBudgetType.FIXED,
        budgetAmount: 35000,
        deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
        status: JobStatus.OPEN,
        images: [
          'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
          'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800',
        ],
        proposalCount: 15,
        viewCount: 312,
        // Interior design specific fields
        designStyle: 'modern-minimalist',
        roomsToDesign: ['open-space', 'conference-room', 'reception', 'kitchen', 'restrooms'],
        furnitureIncluded: true,
        visualizationNeeded: true,
        references: [
          { type: 'pinterest', url: 'https://pinterest.com/pin/123456', title: 'Modern Office Inspiration' },
          { type: 'image', url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800', title: 'Sample office layout' },
          { type: 'link', url: 'https://www.archdaily.com/office-design', title: 'ArchDaily - Office Design Ideas' },
        ],
        preferredColors: ['white', 'gray', 'natural wood', 'green accents'],
        existingFurniture: 'replace-all',
      },
      // Architecture job example
      {
        clientId: clientUser._id,
        title: 'Private House Architecture Design - Tskneti',
        description: 'Need architectural design for a 2-story private house on a hillside plot. Modern Georgian style with large windows and terrace. Looking for architect to create full project from concept to construction documents.',
        category: 'architecture',
        skills: ['architecture', 'project-design', '3d-modeling'],
        location: 'Tbilisi, Tskneti',
        propertyType: JobPropertyType.HOUSE,
        areaSize: 250,
        sizeUnit: JobSizeUnit.SQUARE_METER,
        floorCount: 2,
        budgetType: JobBudgetType.RANGE,
        budgetMin: 15000,
        budgetMax: 25000,
        deadline: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000),
        status: JobStatus.OPEN,
        images: [
          'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
          'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
        ],
        proposalCount: 4,
        viewCount: 89,
        // Architecture specific fields
        cadastralId: '01.19.34.567.890',
        landArea: '1200 sqm',
        projectPhase: 'concept',
        permitRequired: true,
        currentCondition: 'empty-land',
        zoningType: 'residential',
        roomCount: 6,
      },
    ];

    for (const jobData of demoJobs) {
      console.log(`✨ Creating job: ${jobData.title.substring(0, 40)}...`);
      await jobModel.create(jobData);
    }

    console.log(`\n📋 Created ${demoJobs.length} demo jobs`);
  }

  // Create portfolio items for professionals
  console.log('\n🖼️  Creating portfolio items...');

  // Get all pro profiles from database
  const createdProProfiles = await proProfileModel.find({}).populate('userId');
  const allClientUsers = createdUsers.filter(u => u.role === UserRole.CLIENT);

  // Portfolio items data by professional email
  const portfolioData: Record<string, Array<{
    title: string;
    description: string;
    imageUrl: string;
    images?: string[];
    projectType: ProjectType;
    duration: string;
    category: string;
    rating?: number;
    review?: string;
    location: string;
    tags: string[];
    beforeImage?: string;
    afterImage?: string;
  }>> = {
    'giorgi@demo.com': [
      {
        title: 'Smart Home Electrical System Installation',
        description: 'Complete smart home system installation including automated lighting, smart switches, and integrated control panel. Full electrical rewiring for modern efficiency.',
        imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800'],
        projectType: ProjectType.JOB,
        duration: '2 weeks',
        category: 'electrical',
        rating: 5,
        review: 'Giorgi did an amazing job! Very professional and clean work. The smart home system works flawlessly.',
        location: 'Tbilisi, Vake',
        tags: ['smart-home', 'electrical', 'automation'],
        beforeImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        afterImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800',
      },
      {
        title: 'Office Electrical Upgrade',
        description: 'Upgraded electrical system for 200sqm office space. New panel installation, network cabling, and emergency backup system.',
        imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800',
        projectType: ProjectType.PROJECT,
        duration: '1 week',
        category: 'electrical',
        rating: 5,
        review: 'Excellent work! Completed on time and within budget.',
        location: 'Tbilisi, Saburtalo',
        tags: ['electrical', 'commercial', 'upgrade'],
      },
      {
        title: 'Emergency Outlet Repair',
        description: 'Fixed faulty electrical outlets and replaced old wiring in kitchen area. Quick response to urgent request.',
        imageUrl: 'https://images.unsplash.com/photo-1621905252472-943afaa20e20?w=800',
        projectType: ProjectType.QUICK,
        duration: '3 hours',
        category: 'electrical',
        rating: 5,
        review: 'Fast and reliable! Fixed the issue same day.',
        location: 'Tbilisi, Didube',
        tags: ['electrical', 'repair', 'urgent'],
      },
    ],
    'nino@demo.com': [
      {
        title: 'Modern Minimalist Apartment Design',
        description: 'Complete interior design for 120sqm apartment. Scandinavian minimalist style with custom furniture and lighting design.',
        imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800',
        images: ['https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800', 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800'],
        projectType: ProjectType.JOB,
        duration: '3 months',
        category: 'interior-design',
        rating: 5,
        review: 'Nino transformed our apartment into a dream home! Her attention to detail is incredible.',
        location: 'Batumi',
        tags: ['interior-design', 'minimalist', 'modern'],
        beforeImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
        afterImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800',
      },
      {
        title: 'Boutique Hotel Lobby Design',
        description: 'Luxury boutique hotel lobby redesign with Georgian contemporary elements. Custom lighting and furniture selection.',
        imageUrl: 'https://images.unsplash.com/photo-1615529328331-f8917597711f?w=800',
        projectType: ProjectType.JOB,
        duration: '2 months',
        category: 'interior-design',
        rating: 5,
        review: 'Outstanding design! Our guests constantly compliment the new lobby.',
        location: 'Batumi',
        tags: ['interior-design', 'hospitality', 'luxury'],
      },
      {
        title: 'Living Room Refresh',
        description: 'Quick living room makeover with new color scheme, furniture arrangement, and accent pieces.',
        imageUrl: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800',
        projectType: ProjectType.PROJECT,
        duration: '1 week',
        category: 'interior-design',
        rating: 5,
        review: 'Quick turnaround and beautiful results!',
        location: 'Kobuleti',
        tags: ['interior-design', 'refresh', 'living-room'],
      },
    ],
    'davit@demo.com': [
      {
        title: 'Complete Bathroom Plumbing Renovation',
        description: 'Full bathroom plumbing overhaul including new pipes, fixtures, and water heater installation. Modern fixtures with water-saving features.',
        imageUrl: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800',
        projectType: ProjectType.PROJECT,
        duration: '5 days',
        category: 'plumbing',
        rating: 5,
        review: 'Davit is a true professional. No leaks, everything works perfectly!',
        location: 'Kutaisi',
        tags: ['plumbing', 'bathroom', 'renovation'],
        beforeImage: 'https://images.unsplash.com/photo-1564540586988-aa4e53c3d799?w=800',
        afterImage: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800',
      },
      {
        title: 'Emergency Pipe Leak Repair',
        description: 'Urgent repair of burst pipe in apartment building. Quick response prevented water damage.',
        imageUrl: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800',
        projectType: ProjectType.QUICK,
        duration: '2 hours',
        category: 'plumbing',
        rating: 5,
        review: 'Came within 30 minutes and fixed the issue immediately. Saved us from disaster!',
        location: 'Kutaisi',
        tags: ['plumbing', 'emergency', 'repair'],
      },
      {
        title: 'Kitchen Sink and Dishwasher Installation',
        description: 'Installed new kitchen sink, faucet, and connected dishwasher with proper drainage.',
        imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
        projectType: ProjectType.QUICK,
        duration: '4 hours',
        category: 'plumbing',
        rating: 4,
        review: 'Good work, reasonably priced.',
        location: 'Zestafoni',
        tags: ['plumbing', 'kitchen', 'installation'],
      },
    ],
    'mariam@demo.com': [
      {
        title: 'Full Apartment Renovation - Saburtalo',
        description: 'Complete 85sqm apartment renovation. Wall leveling, painting, new flooring, bathroom remodel, and kitchen update.',
        imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800', 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'],
        projectType: ProjectType.JOB,
        duration: '2 months',
        category: 'renovation',
        rating: 5,
        review: 'Mariam and her team did an exceptional job! The apartment looks brand new.',
        location: 'Tbilisi, Saburtalo',
        tags: ['renovation', 'full-remodel', 'residential'],
        beforeImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
        afterImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      },
      {
        title: 'Bedroom Renovation',
        description: 'Master bedroom renovation with new flooring, wall treatment, and built-in closet installation.',
        imageUrl: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800',
        projectType: ProjectType.PROJECT,
        duration: '2 weeks',
        category: 'renovation',
        rating: 5,
        review: 'Beautiful work! Love my new bedroom.',
        location: 'Tbilisi, Rustavi',
        tags: ['renovation', 'bedroom', 'flooring'],
      },
      {
        title: 'Wall Painting - 3 Rooms',
        description: 'Interior painting for three rooms with wall preparation and premium paint application.',
        imageUrl: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800',
        projectType: ProjectType.PROJECT,
        duration: '4 days',
        category: 'painting',
        rating: 5,
        review: 'Clean work and beautiful finish!',
        location: 'Mtskheta',
        tags: ['painting', 'interior', 'residential'],
      },
    ],
    'ana@demo.com': [
      {
        title: 'Modern Kitchen Design & Installation',
        description: 'Complete kitchen design with custom cabinets, island installation, and premium countertops. Included 3D visualization.',
        imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
        images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800', 'https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=800'],
        projectType: ProjectType.JOB,
        duration: '6 weeks',
        category: 'kitchen',
        rating: 5,
        review: 'Ana designed our dream kitchen! The 3D preview was exactly what we got.',
        location: 'Rustavi',
        tags: ['kitchen', 'design', 'custom-cabinets'],
        beforeImage: 'https://images.unsplash.com/photo-1556909190-eccf4a8bf97a?w=800',
        afterImage: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
      },
      {
        title: 'Kitchen Cabinet Refinishing',
        description: 'Refinished existing cabinets with new doors and hardware. Cost-effective kitchen refresh.',
        imageUrl: 'https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=800',
        projectType: ProjectType.PROJECT,
        duration: '1 week',
        category: 'kitchen',
        rating: 5,
        review: 'Saved money by refinishing instead of replacing. Looks amazing!',
        location: 'Tbilisi',
        tags: ['kitchen', 'cabinets', 'refinishing'],
      },
    ],
    'zura@demo.com': [
      {
        title: 'Custom Built-in Bookshelf',
        description: 'Floor-to-ceiling built-in bookshelf with integrated lighting. Solid wood construction with custom finish.',
        imageUrl: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=800',
        projectType: ProjectType.PROJECT,
        duration: '2 weeks',
        category: 'carpentry',
        rating: 5,
        review: 'Zura is a master craftsman! The bookshelf is a work of art.',
        location: 'Tbilisi',
        tags: ['carpentry', 'custom-furniture', 'bookshelf'],
      },
      {
        title: 'Wooden Staircase Restoration',
        description: 'Complete restoration of antique wooden staircase. Repair, sanding, and refinishing with original design.',
        imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800',
        projectType: ProjectType.JOB,
        duration: '3 weeks',
        category: 'carpentry',
        rating: 5,
        review: 'Brought our 100-year-old staircase back to life!',
        location: 'Mtskheta',
        tags: ['carpentry', 'restoration', 'antique'],
        beforeImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        afterImage: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800',
      },
      {
        title: 'Custom Dining Table',
        description: 'Handcrafted solid walnut dining table for 8 people. Custom design with live edge.',
        imageUrl: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800',
        projectType: ProjectType.PROJECT,
        duration: '3 weeks',
        category: 'furniture',
        rating: 5,
        review: 'The table is absolutely stunning. Worth every penny!',
        location: 'Tbilisi',
        tags: ['carpentry', 'furniture', 'dining-table'],
      },
    ],
    'irakli@demo.com': [
      {
        title: 'Full Apartment Interior Painting',
        description: 'Complete interior painting for 100sqm apartment. Wall preparation, primer, and two coats of premium paint.',
        imageUrl: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800',
        projectType: ProjectType.PROJECT,
        duration: '1 week',
        category: 'painting',
        rating: 5,
        review: 'Perfect finish, clean work, and fair price!',
        location: 'Tbilisi, Rustavi',
        tags: ['painting', 'interior', 'apartment'],
      },
      {
        title: 'Decorative Wall Texture',
        description: 'Applied decorative textured finish to accent wall. Venetian plaster technique.',
        imageUrl: 'https://images.unsplash.com/photo-1615529328331-f8917597711f?w=800',
        projectType: ProjectType.QUICK,
        duration: '2 days',
        category: 'painting',
        rating: 5,
        review: 'The texture is beautiful! Adds so much character to the room.',
        location: 'Tbilisi',
        tags: ['painting', 'decorative', 'texture'],
      },
      {
        title: 'Exterior House Painting',
        description: 'Complete exterior painting for two-story private house. Weather-resistant paint with 10-year guarantee.',
        imageUrl: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800',
        projectType: ProjectType.JOB,
        duration: '2 weeks',
        category: 'painting',
        rating: 5,
        review: 'House looks brand new! Great attention to detail.',
        location: 'Mtskheta',
        tags: ['painting', 'exterior', 'residential'],
        beforeImage: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
        afterImage: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800',
      },
    ],
    'tamari@demo.com': [
      {
        title: 'Modern Garden Design',
        description: 'Complete garden redesign with native plants, irrigation system, and outdoor lighting.',
        imageUrl: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=800',
        projectType: ProjectType.JOB,
        duration: '1 month',
        category: 'landscape',
        rating: 5,
        review: 'Tamari created a beautiful oasis! The garden is now our favorite place.',
        location: 'Batumi',
        tags: ['landscape', 'garden', 'design'],
        beforeImage: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
        afterImage: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=800',
      },
      {
        title: 'Patio and Walkway Installation',
        description: 'Installed stone patio with decorative walkway. Included drainage system and garden beds.',
        imageUrl: 'https://images.unsplash.com/photo-1598902108854-10e335adac99?w=800',
        projectType: ProjectType.PROJECT,
        duration: '2 weeks',
        category: 'outdoor',
        rating: 5,
        review: 'Beautiful hardscaping work. Very professional!',
        location: 'Kobuleti',
        tags: ['landscape', 'patio', 'hardscaping'],
      },
    ],
    'elene@demo.com': [
      {
        title: 'Hardwood Floor Installation',
        description: 'Installed premium oak hardwood flooring in 80sqm apartment. Including subfloor preparation and finishing.',
        imageUrl: 'https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=800',
        projectType: ProjectType.PROJECT,
        duration: '1 week',
        category: 'flooring',
        rating: 5,
        review: 'The floors are gorgeous! Expert installation.',
        location: 'Kutaisi',
        tags: ['flooring', 'hardwood', 'installation'],
        beforeImage: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800',
        afterImage: 'https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=800',
      },
      {
        title: 'Tile Flooring - Bathroom',
        description: 'Installed porcelain tile flooring with heated floor system. Waterproofing included.',
        imageUrl: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800',
        projectType: ProjectType.PROJECT,
        duration: '5 days',
        category: 'tiling',
        rating: 5,
        review: 'Perfect tile work and the heated floor is amazing!',
        location: 'Tbilisi',
        tags: ['flooring', 'tiling', 'bathroom'],
      },
    ],
    'sophio@demo.com': [
      {
        title: 'Post-Construction Deep Clean',
        description: 'Complete post-construction cleaning for newly renovated 120sqm apartment. All surfaces, windows, and fixtures.',
        imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800',
        projectType: ProjectType.QUICK,
        duration: '1 day',
        category: 'cleaning',
        rating: 5,
        review: 'Apartment was spotless after the renovation mess!',
        location: 'Tbilisi',
        tags: ['cleaning', 'post-construction', 'deep-clean'],
      },
      {
        title: 'Regular Home Cleaning Service',
        description: 'Weekly cleaning service for private home. Kitchen, bathrooms, living areas, and bedrooms.',
        imageUrl: 'https://images.unsplash.com/photo-1527515545081-5db817172677?w=800',
        projectType: ProjectType.QUICK,
        duration: '4 hours',
        category: 'cleaning',
        rating: 5,
        review: 'Best cleaning service! Always thorough and reliable.',
        location: 'Rustavi',
        tags: ['cleaning', 'regular', 'residential'],
      },
    ],
    'levan@demo.com': [
      {
        title: 'Home Security System Installation',
        description: 'Complete home security setup with 8 cameras, motion sensors, smart locks, and 24/7 monitoring connection.',
        imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800',
        images: ['https://images.unsplash.com/photo-1558002038-1055907df827?w=800', 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800'],
        projectType: ProjectType.PROJECT,
        duration: '3 days',
        category: 'security',
        rating: 5,
        review: 'Feel so much safer now! Great system and professional installation.',
        location: 'Rustavi',
        tags: ['security', 'smart-home', 'cctv'],
      },
      {
        title: 'Office Access Control System',
        description: 'Installed card access system for office building. 4 entry points with logging and remote management.',
        imageUrl: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800',
        images: ['https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800', 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800'],
        projectType: ProjectType.PROJECT,
        duration: '1 week',
        category: 'security',
        rating: 5,
        review: 'Works perfectly! Easy to manage and very secure.',
        location: 'Tbilisi',
        tags: ['security', 'access-control', 'commercial'],
      },
      {
        title: 'Villa Perimeter Security',
        description: 'Comprehensive perimeter security with motion-activated cameras, night vision, and mobile app integration.',
        imageUrl: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800',
        images: ['https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800', 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800', 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800'],
        projectType: ProjectType.JOB,
        duration: '2 weeks',
        category: 'security',
        rating: 5,
        review: 'Best security system we could ask for. Professional installation and great support.',
        location: 'Gardabani',
        tags: ['security', 'villa', 'perimeter'],
      },
    ],
    'luka@demo.com': [
      {
        title: 'Central AC Installation - Office Building',
        description: 'Complete central air conditioning system for 500sqm office space. Ductwork, multiple zones, and smart thermostat integration.',
        imageUrl: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800',
        images: ['https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800', 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800', 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800'],
        projectType: ProjectType.JOB,
        duration: '2 weeks',
        category: 'hvac',
        rating: 5,
        review: 'Amazing work! The office is now perfectly climate controlled. Energy bills are lower than expected.',
        location: 'Tbilisi, Saburtalo',
        tags: ['hvac', 'commercial', 'ac-installation'],
      },
      {
        title: 'Heat Pump System Installation',
        description: 'Energy-efficient heat pump for heating and cooling. Includes outdoor unit, indoor handlers, and thermostat setup.',
        imageUrl: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800',
        images: ['https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
        projectType: ProjectType.PROJECT,
        duration: '4 days',
        category: 'hvac',
        rating: 5,
        review: 'Great energy savings! Luka explained everything clearly and the installation was spotless.',
        location: 'Rustavi',
        tags: ['hvac', 'heat-pump', 'energy-efficient'],
      },
      {
        title: 'AC Repair & Maintenance',
        description: 'Emergency AC repair - compressor issue fixed and full system maintenance performed.',
        imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800',
        projectType: ProjectType.QUICK,
        duration: '4 hours',
        category: 'hvac',
        rating: 5,
        review: 'Fast response on a hot summer day! AC is running better than before.',
        location: 'Tbilisi, Vake',
        tags: ['hvac', 'repair', 'maintenance'],
      },
    ],
    'ketevan@demo.com': [
      {
        title: 'Pre-Purchase Home Inspection',
        description: 'Comprehensive inspection for home buyer. 150-page detailed report with photos covering structure, electrical, plumbing, and more.',
        imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
        images: ['https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800'],
        projectType: ProjectType.PROJECT,
        duration: '1 day',
        category: 'inspection',
        rating: 5,
        review: 'The report saved us from buying a house with major foundation issues. Worth every lari!',
        location: 'Tbilisi, Didube',
        tags: ['inspection', 'pre-purchase', 'home-buyer'],
      },
      {
        title: 'Thermal Imaging Assessment',
        description: 'Used infrared camera to detect heat loss, moisture intrusion, and electrical hotspots throughout the property.',
        imageUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
        images: ['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800', 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800'],
        projectType: ProjectType.PROJECT,
        duration: '3 hours',
        category: 'inspection',
        rating: 5,
        review: 'Found hidden moisture problem we never knew about. Very thorough and professional.',
        location: 'Mtskheta',
        tags: ['inspection', 'thermal-imaging', 'moisture'],
      },
      {
        title: 'Safety Inspection for Rental Property',
        description: 'Complete safety assessment for landlord - electrical safety, fire hazards, structural concerns documented.',
        imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
        projectType: ProjectType.QUICK,
        duration: '2 hours',
        category: 'inspection',
        rating: 4,
        review: 'Quick and professional. Report was ready same day.',
        location: 'Rustavi',
        tags: ['inspection', 'safety', 'rental'],
      },
    ],
    'giga@demo.com': [
      {
        title: 'Luxury Pool Installation - Batumi Villa',
        description: 'Built 8x4m infinity pool with heating system, LED lighting, and automatic chlorination. Includes surrounding deck installation.',
        imageUrl: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800',
        images: ['https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800', 'https://images.unsplash.com/photo-1572331165267-854da2b10ccc?w=800', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800'],
        projectType: ProjectType.JOB,
        duration: '6 weeks',
        category: 'pool',
        rating: 5,
        review: 'Dream pool became reality! Giga and his team exceeded all expectations.',
        location: 'Batumi',
        tags: ['pool', 'installation', 'luxury'],
        beforeImage: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=800',
        afterImage: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800',
      },
      {
        title: 'Pool Renovation & Upgrade',
        description: 'Renovated 15-year-old pool - new tiles, modern filtration system, energy-efficient pump, and salt chlorination.',
        imageUrl: 'https://images.unsplash.com/photo-1572331165267-854da2b10ccc?w=800',
        images: ['https://images.unsplash.com/photo-1572331165267-854da2b10ccc?w=800', 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800'],
        projectType: ProjectType.PROJECT,
        duration: '2 weeks',
        category: 'pool',
        rating: 5,
        review: 'Our old pool looks brand new! Water quality is amazing now.',
        location: 'Kobuleti',
        tags: ['pool', 'renovation', 'upgrade'],
      },
      {
        title: 'Seasonal Pool Opening & Maintenance',
        description: 'Complete spring pool opening - cleaning, equipment check, chemical balancing, and leak detection.',
        imageUrl: 'https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=800',
        projectType: ProjectType.QUICK,
        duration: '1 day',
        category: 'pool',
        rating: 5,
        review: 'Pool was ready for summer in no time. Very reliable service.',
        location: 'Chakvi',
        tags: ['pool', 'maintenance', 'seasonal'],
      },
    ],
    'nana@demo.com': [
      {
        title: 'Full House Move - Tbilisi to Batumi',
        description: 'Long-distance move for 4-bedroom house. Professional packing, custom crating for valuables, and same-day delivery.',
        imageUrl: 'https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=800',
        images: ['https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=800', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800'],
        projectType: ProjectType.JOB,
        duration: '2 days',
        category: 'moving',
        rating: 5,
        review: 'Not a single item damaged! Team was careful with our antique furniture. Highly recommend.',
        location: 'Tbilisi → Batumi',
        tags: ['moving', 'long-distance', 'full-service'],
      },
      {
        title: 'Office Relocation',
        description: 'Moved 30-person office including IT equipment, furniture disassembly/assembly, and weekend timing to minimize downtime.',
        imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
        images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800', 'https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=800'],
        projectType: ProjectType.PROJECT,
        duration: '1 weekend',
        category: 'moving',
        rating: 5,
        review: 'Incredible efficiency! Office was operational Monday morning.',
        location: 'Tbilisi',
        tags: ['moving', 'commercial', 'office'],
      },
      {
        title: 'Apartment Move with Storage',
        description: 'Moved 2-bedroom apartment with 1 month storage while new home was being renovated.',
        imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        projectType: ProjectType.PROJECT,
        duration: '1 day + storage',
        category: 'moving',
        rating: 4,
        review: 'Good service, storage facility was clean and secure.',
        location: 'Rustavi',
        tags: ['moving', 'storage', 'apartment'],
      },
    ],
    'nikoloz@demo.com': [
      {
        title: 'Complete Roof Replacement - Tile to Metal',
        description: 'Replaced old clay tile roof with modern metal roofing. Includes insulation upgrade and new gutters.',
        imageUrl: 'https://images.unsplash.com/photo-1632759145351-1d592919f522?w=800',
        images: ['https://images.unsplash.com/photo-1632759145351-1d592919f522?w=800', 'https://images.unsplash.com/photo-1558036117-15d82a90b9b1?w=800', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800'],
        projectType: ProjectType.JOB,
        duration: '10 days',
        category: 'roofing',
        rating: 5,
        review: 'Amazing transformation! House looks completely new. No more leaks!',
        location: 'Mtskheta',
        tags: ['roofing', 'metal-roof', 'full-replacement'],
        beforeImage: 'https://images.unsplash.com/photo-1558036117-15d82a90b9b1?w=800',
        afterImage: 'https://images.unsplash.com/photo-1632759145351-1d592919f522?w=800',
      },
      {
        title: 'Flat Roof Waterproofing',
        description: 'Applied EPDM membrane waterproofing on 200sqm flat roof. 15-year warranty on materials.',
        imageUrl: 'https://images.unsplash.com/photo-1558036117-15d82a90b9b1?w=800',
        images: ['https://images.unsplash.com/photo-1558036117-15d82a90b9b1?w=800', 'https://images.unsplash.com/photo-1632759145351-1d592919f522?w=800'],
        projectType: ProjectType.PROJECT,
        duration: '3 days',
        category: 'roofing',
        rating: 5,
        review: 'Finally no more water damage! Very professional work.',
        location: 'Tbilisi',
        tags: ['roofing', 'waterproofing', 'flat-roof'],
      },
      {
        title: 'Emergency Storm Damage Repair',
        description: 'Emergency repair after storm - replaced missing tiles, fixed flashing, and secured loose sections.',
        imageUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
        projectType: ProjectType.QUICK,
        duration: '6 hours',
        category: 'roofing',
        rating: 5,
        review: 'Came immediately after the storm. Prevented further water damage.',
        location: 'Rustavi',
        tags: ['roofing', 'emergency', 'storm-damage'],
      },
    ],
  };

  let portfolioCount = 0;
  for (const profile of createdProProfiles) {
    const userEmail = (profile.userId as any).email;
    const items = portfolioData[userEmail];

    if (items && items.length > 0) {
      for (let i = 0; i < items.length; i++) {
        const item = items[i];
        // Assign a random client from the list
        const randomClient = allClientUsers[Math.floor(Math.random() * allClientUsers.length)];

        await portfolioModel.create({
          proId: profile._id,
          title: item.title,
          description: item.description,
          imageUrl: item.imageUrl,
          images: item.images || [item.imageUrl],
          tags: item.tags,
          projectDate: new Date(Date.now() - (i + 1) * 30 * 24 * 60 * 60 * 1000),
          completedDate: new Date(Date.now() - i * 30 * 24 * 60 * 60 * 1000),
          location: item.location,
          displayOrder: i,
          projectType: item.projectType,
          status: ProjectStatus.COMPLETED,
          clientId: randomClient._id,
          clientName: randomClient.name,
          clientAvatar: randomClient.avatar || '',
          clientCity: randomClient.city,
          duration: item.duration,
          category: item.category,
          rating: item.rating,
          review: item.review,
          beforeImage: item.beforeImage,
          afterImage: item.afterImage,
        });
        portfolioCount++;
      }
      console.log(`✨ Created ${items.length} portfolio items for: ${userEmail}`);
    }
  }

  console.log(`\n📋 Created ${portfolioCount} portfolio items total`);

  // =====================
  // CREATE COMPANIES
  // =====================
  console.log('\n🏢 Creating companies...');

  // Company owner users
  const companyOwnerUsers = [
    {
      name: 'Giorgi Maisuradze',
      email: 'company1@demo.com',
      password: hashedPassword,
      role: UserRole.COMPANY,
      phone: '+995 555 800 001',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Nino Gorgadze',
      email: 'company2@demo.com',
      password: hashedPassword,
      role: UserRole.COMPANY,
      phone: '+995 555 800 002',
      city: 'Batumi',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
    {
      name: 'Davit Kapanadze',
      email: 'company3@demo.com',
      password: hashedPassword,
      role: UserRole.COMPANY,
      phone: '+995 555 800 003',
      city: 'Tbilisi',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
      isActive: true,
      idNumber: generateIdNumber(),
    },
  ];

  const createdCompanyOwners: User[] = [];
  for (const userData of companyOwnerUsers) {
    let user = await userModel.findOne({ email: userData.email });
    if (!user) {
      console.log(`✨ Creating company owner: ${userData.email}`);
      user = await userModel.create(userData);
    }
    createdCompanyOwners.push(user);
  }

  // Company data
  const companiesData = [
    {
      ownerEmail: 'company1@demo.com',
      company: {
        name: 'ProBuild Georgia',
        legalName: 'ProBuild Georgia LLC',
        description: 'Full-service construction and renovation company with over 10 years of experience. We handle everything from small repairs to complete home transformations.',
        tagline: 'Building Dreams, Renovating Lives',
        email: 'info@probuild.ge',
        phone: '+995 322 800 001',
        website: 'https://probuild.ge',
        address: '45 Chavchavadze Avenue',
        city: 'Tbilisi',
        country: 'Georgia',
        taxId: 'GE123456789',
        foundedYear: 2014,
        size: CompanySize.MEDIUM,
        categories: ['renovation', 'construction', 'painting', 'flooring', 'plumbing', 'electrical'],
        serviceAreas: ['Tbilisi', 'Rustavi', 'Mtskheta', 'Gardabani'],
        certifications: ['ISO 9001', 'Licensed General Contractor', 'Safety Certified'],
        languages: ['Georgian', 'English', 'Russian'],
        logo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=200&h=200&fit=crop',
        coverImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&h=400&fit=crop',
        status: CompanyStatus.ACTIVE,
        isVerified: true,
        verifiedAt: new Date(),
        avgRating: 4.8,
        totalReviews: 156,
        completedJobs: 342,
        activeWorkers: 12,
        acceptingJobs: true,
        isHiring: true,
        workingHours: {
          monday: { open: '09:00', close: '18:00', closed: false },
          tuesday: { open: '09:00', close: '18:00', closed: false },
          wednesday: { open: '09:00', close: '18:00', closed: false },
          thursday: { open: '09:00', close: '18:00', closed: false },
          friday: { open: '09:00', close: '18:00', closed: false },
          saturday: { open: '10:00', close: '15:00', closed: false },
          sunday: { open: '', close: '', closed: true },
        },
        plan: 'premium',
      },
      employees: [
        {
          name: 'Sandro Mgeladze',
          email: 'sandro.worker@demo.com',
          phone: '+995 555 801 001',
          role: EmployeeRole.MANAGER,
          jobTitle: 'Project Manager',
          skills: ['project-management', 'renovation', 'client-relations'],
          department: 'Operations',
        },
        {
          name: 'Levan Chkheidze',
          email: 'levan.worker@demo.com',
          phone: '+995 555 801 002',
          role: EmployeeRole.WORKER,
          jobTitle: 'Senior Electrician',
          skills: ['electrical', 'smart-home', 'wiring'],
          department: 'Electrical',
        },
        {
          name: 'Dato Janelidze',
          email: 'dato.worker@demo.com',
          phone: '+995 555 801 003',
          role: EmployeeRole.WORKER,
          jobTitle: 'Master Plumber',
          skills: ['plumbing', 'bathroom', 'heating'],
          department: 'Plumbing',
        },
        {
          name: 'Nika Tsereteli',
          email: 'nika.worker@demo.com',
          phone: '+995 555 801 004',
          role: EmployeeRole.WORKER,
          jobTitle: 'Painter',
          skills: ['painting', 'wallpaper', 'texture'],
          department: 'Finishing',
        },
      ],
    },
    {
      ownerEmail: 'company2@demo.com',
      company: {
        name: 'Coastal Designs',
        legalName: 'Coastal Designs LLC',
        description: 'Award-winning interior design and renovation studio specializing in coastal and Mediterranean styles. Transforming spaces with elegance.',
        tagline: 'Where Design Meets the Sea',
        email: 'hello@coastaldesigns.ge',
        phone: '+995 422 800 002',
        website: 'https://coastaldesigns.ge',
        address: '12 Rustaveli Street',
        city: 'Batumi',
        country: 'Georgia',
        taxId: 'GE987654321',
        foundedYear: 2018,
        size: CompanySize.SMALL,
        categories: ['interior-design', 'renovation', 'furniture'],
        serviceAreas: ['Batumi', 'Kobuleti', 'Chakvi', 'Gonio'],
        certifications: ['Interior Design Diploma', 'AutoCAD Certified'],
        languages: ['Georgian', 'English', 'Turkish', 'Russian'],
        logo: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=200&h=200&fit=crop',
        coverImage: 'https://images.unsplash.com/photo-1615529328331-f8917597711f?w=1200&h=400&fit=crop',
        status: CompanyStatus.ACTIVE,
        isVerified: true,
        verifiedAt: new Date(),
        avgRating: 4.9,
        totalReviews: 67,
        completedJobs: 89,
        activeWorkers: 5,
        acceptingJobs: true,
        isHiring: false,
        workingHours: {
          monday: { open: '10:00', close: '19:00', closed: false },
          tuesday: { open: '10:00', close: '19:00', closed: false },
          wednesday: { open: '10:00', close: '19:00', closed: false },
          thursday: { open: '10:00', close: '19:00', closed: false },
          friday: { open: '10:00', close: '19:00', closed: false },
          saturday: { open: '11:00', close: '16:00', closed: false },
          sunday: { open: '', close: '', closed: true },
        },
        plan: 'basic',
      },
      employees: [
        {
          name: 'Mariam Diasamidze',
          email: 'mariam.design@demo.com',
          phone: '+995 555 802 001',
          role: EmployeeRole.WORKER,
          jobTitle: 'Interior Designer',
          skills: ['interior-design', '3d-visualization', 'furniture-selection'],
          department: 'Design',
        },
        {
          name: 'Giorgi Lomidze',
          email: 'giorgi.design@demo.com',
          phone: '+995 555 802 002',
          role: EmployeeRole.WORKER,
          jobTitle: 'Renovation Specialist',
          skills: ['renovation', 'painting', 'flooring'],
          department: 'Execution',
        },
      ],
    },
    {
      ownerEmail: 'company3@demo.com',
      company: {
        name: 'TechHome Solutions',
        legalName: 'TechHome Solutions LLC',
        description: 'Smart home technology and security systems specialists. We bring your home into the future with cutting-edge automation solutions.',
        tagline: 'Smart Living, Secure Future',
        email: 'support@techhome.ge',
        phone: '+995 322 800 003',
        website: 'https://techhome.ge',
        address: '78 Pekini Avenue',
        city: 'Tbilisi',
        country: 'Georgia',
        taxId: 'GE456789123',
        foundedYear: 2020,
        size: CompanySize.SMALL,
        categories: ['smart-home', 'security', 'electrical', 'hvac'],
        serviceAreas: ['Tbilisi', 'Rustavi', 'Mtskheta'],
        certifications: ['Smart Home Certified', 'Security Systems Installer', 'Network Security'],
        languages: ['Georgian', 'English'],
        logo: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=200&h=200&fit=crop',
        coverImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=400&fit=crop',
        status: CompanyStatus.ACTIVE,
        isVerified: true,
        verifiedAt: new Date(),
        avgRating: 4.7,
        totalReviews: 43,
        completedJobs: 78,
        activeWorkers: 4,
        acceptingJobs: true,
        isHiring: true,
        workingHours: {
          monday: { open: '09:00', close: '18:00', closed: false },
          tuesday: { open: '09:00', close: '18:00', closed: false },
          wednesday: { open: '09:00', close: '18:00', closed: false },
          thursday: { open: '09:00', close: '18:00', closed: false },
          friday: { open: '09:00', close: '18:00', closed: false },
          saturday: { open: '', close: '', closed: true },
          sunday: { open: '', close: '', closed: true },
        },
        plan: 'basic',
      },
      employees: [
        {
          name: 'Tornike Beridze',
          email: 'tornike.tech@demo.com',
          phone: '+995 555 803 001',
          role: EmployeeRole.WORKER,
          jobTitle: 'Smart Home Technician',
          skills: ['smart-home', 'automation', 'networking'],
          department: 'Technical',
        },
        {
          name: 'Zurab Gelashvili',
          email: 'zurab.tech@demo.com',
          phone: '+995 555 803 002',
          role: EmployeeRole.WORKER,
          jobTitle: 'Security Systems Expert',
          skills: ['security', 'cctv', 'access-control'],
          department: 'Security',
        },
      ],
    },
  ];

  const createdCompanies: any[] = [];
  for (const companyData of companiesData) {
    const owner = createdCompanyOwners.find(u => u.email === companyData.ownerEmail);
    if (!owner) continue;

    console.log(`✨ Creating company: ${companyData.company.name}`);

    const company = await companyModel.create({
      ...companyData.company,
      ownerId: owner._id,
    });

    createdCompanies.push(company);

    // Create owner as employee
    await companyEmployeeModel.create({
      companyId: company._id,
      userId: owner._id,
      name: owner.name,
      email: owner.email,
      role: EmployeeRole.OWNER,
      status: EmployeeStatus.ACTIVE,
      jobTitle: 'Owner',
      permissions: {
        canViewJobs: true,
        canAcceptJobs: true,
        canManageWorkers: true,
        canManageCompany: true,
        canViewFinances: true,
        canMessageClients: true,
      },
      hireDate: new Date(),
    });

    // Create other employees
    for (const empData of companyData.employees) {
      await companyEmployeeModel.create({
        companyId: company._id,
        name: empData.name,
        email: empData.email.toLowerCase(),
        phone: empData.phone,
        role: empData.role,
        jobTitle: empData.jobTitle,
        skills: empData.skills,
        department: empData.department,
        status: EmployeeStatus.ACTIVE,
        hireDate: new Date(Date.now() - Math.random() * 365 * 24 * 60 * 60 * 1000),
        permissions: {
          canViewJobs: true,
          canAcceptJobs: empData.role === EmployeeRole.MANAGER,
          canManageWorkers: empData.role === EmployeeRole.MANAGER,
          canManageCompany: false,
          canViewFinances: empData.role === EmployeeRole.MANAGER,
          canMessageClients: true,
        },
      });
    }

    console.log(`   ✓ Created ${companyData.employees.length + 1} employees`);
  }

  // Create sample company jobs
  console.log('\n📋 Creating company jobs...');
  const firstCompany = createdCompanies[0];
  const sampleClients = allClientUsers.slice(0, 3);

  if (firstCompany && sampleClients.length > 0) {
    const companyJobs = [
      {
        companyId: firstCompany._id,
        clientId: sampleClients[0]._id,
        clientName: sampleClients[0].name,
        clientPhone: sampleClients[0].phone,
        title: 'Full Apartment Renovation - Vake',
        description: 'Complete renovation of 95sqm apartment including all rooms, kitchen, and bathrooms.',
        category: 'renovation',
        skills: ['renovation', 'painting', 'flooring', 'plumbing'],
        location: 'Tbilisi, Vake',
        address: '23 Ilia Chavchavadze Ave, Apt 15',
        scheduledDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        scheduledTime: '09:00',
        estimatedDuration: '6 weeks',
        deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        priority: JobPriority.HIGH,
        quotedPrice: 28000,
        currency: 'GEL',
        status: CompanyJobStatus.IN_PROGRESS,
        tags: ['residential', 'full-renovation'],
      },
      {
        companyId: firstCompany._id,
        clientId: sampleClients[1]._id,
        clientName: sampleClients[1].name,
        clientPhone: sampleClients[1].phone,
        title: 'Bathroom Remodel',
        description: 'Complete bathroom renovation with new tiles, fixtures, and waterproofing.',
        category: 'bathroom',
        skills: ['plumbing', 'tiling', 'waterproofing'],
        location: 'Tbilisi, Saburtalo',
        address: '45 Vazha Pshavela Ave, Apt 8',
        scheduledDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        scheduledTime: '10:00',
        estimatedDuration: '2 weeks',
        priority: JobPriority.MEDIUM,
        quotedPrice: 4500,
        currency: 'GEL',
        status: CompanyJobStatus.ASSIGNED,
        tags: ['bathroom', 'renovation'],
      },
      {
        companyId: firstCompany._id,
        clientId: sampleClients[2]._id,
        clientName: sampleClients[2].name,
        clientPhone: sampleClients[2].phone,
        title: 'Office Painting - 150sqm',
        description: 'Interior painting for office space. Wall preparation and premium paint application.',
        category: 'painting',
        skills: ['painting'],
        location: 'Tbilisi, Vera',
        address: '12 Melikishvili Street',
        scheduledDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        scheduledTime: '08:00',
        estimatedDuration: '1 week',
        priority: JobPriority.LOW,
        quotedPrice: 3000,
        currency: 'GEL',
        status: CompanyJobStatus.PENDING,
        tags: ['commercial', 'painting'],
      },
    ];

    for (const jobData of companyJobs) {
      await companyJobModel.create(jobData);
    }

    console.log(`   ✓ Created ${companyJobs.length} company jobs`);
  }

  console.log(`\n🏢 Created ${createdCompanies.length} companies with employees`);

  console.log('\n✅ Seed completed successfully!');
  console.log('\n📋 Demo accounts:');
  console.log('   Client: client@demo.com / demo123');
  console.log('   Admin: admin@demo.com / demo123');
  console.log('\n   Company accounts:');
  companyOwnerUsers.forEach(u => console.log(`   ${u.email} / demo123`));
  console.log('\n   Pro accounts (16 professionals):');
  proUsers.forEach(u => console.log(`   ${u.email} / demo123`));
  console.log(`\n📋 Demo jobs: 6 open jobs created`);
  console.log(`📋 Portfolio items: ${portfolioCount} items created`);
  console.log(`🏢 Companies: ${createdCompanies.length} companies with employees`);

  await app.close();
  process.exit(0);
}

seed().catch((error) => {
  console.error('❌ Seed failed:', error);
  process.exit(1);
});
